=== lg/awardwiz/awardwiz/config.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "excludeAirlines": {
      "type": "array",
      "description": "Airline codes for airlines which should not be processed (ex. cargo airlines like FX)",
      "items": {
        "type": "string",
        "minLength": 2
      }
    },
    "chaseUnsupportedAirlines": {
      "type": "array",
      "description": "Chase Ultimate Rewards only supports some airlines for booking cash fares, list the ones it doesn't here (ex. WN)",
      "items": {
        "type": "string",
        "minLength": 2
      }
    },
    "airlineGroups": {
      "type": "object",
      "description": "Group name to array of airlines mapping (ex. for use with an airline alliance)",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 2
        }
      }
    },
    "saverBookingClasses": {
      "type": "object",
      "description": "Booking classes list for each airline which should be considered saver fares (and bookable using partners' miles). Supports airlineGroups.",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1,
          "maxLength": 2
        }
      }
    },
    "airlineAmenities": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "airlineCode": {
            "type": "string",
            "description": "Airline IATA code (ex. 'UA')"
          },
          "podsAircraft": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Substrings of aircraft names to assume have lie-flat seats in Business (ex. 'A321'). Use '*' to match all aircrafts by the airline."
          },
          "wifiAircraft": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Substrings of aircraft names to assume have wifi (ex. 'A321'). Use '*' to match all aircrafts by the airline."
          }
        },
        "title": "AirlineAmenity"
      }
    },
    "scrapers": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the scraper (ex. 'united')"
          },
          "disabled": {
            "type": "boolean",
            "description": "Disables the scraper from being selected"
          },
          "supportedAirlines": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 2
            },
            "description": "Codes of the airlines which this scraper searches (ex. 'UA')"
          },
          "nativeAirline": {
            "type": ["string", "null"],
            "description": "Code of the airline which this scraper naturally searches. Results with this ariline will not be assumed to be saver awards."
          },
          "cashOnlyFares": {
            "type": "boolean",
            "default": false,
            "description": "Set this to true to have this scraper be called for all airlines and to convert all fares on a cents-per-mile basis"
          }
        },
        "required": [
          "name",
          "supportedAirlines"
        ],
        "title": "Scraper"
      }
    }
  },
  "required": [
    "scrapers"
  ],
  "title": "ScrapersConfig"
}

=== lg/awardwiz/awardwiz/config.json
{
  "$schema": "./config.schema.json",
  "airlineAmenities": [
    {
      "airlineCode": "AC",
      "podsAircraft": ["A330", "787", "777"],
      "wifiAircraft": ["A321", "A319", "A320", "E175", "CRJ900", "E90", "777-300", "777-200", "220-300"]
    },
    {
      "airlineCode": "UA",
      "podsAircraft": ["787", "777", "757-200", "767"],
      "wifiAircraft": ["170", "175", "700", "550", "A320", "767-300", "767-400", "777-200", "777-300", "787-8", "787-9", "787-10", "737-700", "737-800", "737-900", "737 MAX", "757-200"]
    },
    {
      "airlineCode": "B6",
      "podsAircraft": ["Mint", "A321"],
      "wifiAircraft": ["*"]
    },
    {
      "airlineCode": "WN",
      "podsAircraft": [],
      "wifiAircraft": ["*"]
    },
    {
      "airlineCode": "AS",
      "podsAircraft": [],
      "wifiAircraft": ["E175", "737-900", "A320", "A321", "737-800", "737-700"]
    },
    {
      "airlineCode": "HA",
      "podsAircraft": []
    }
  ],
  "airlineGroups": {
    "staralliance": ["AC", "JP", "A3", "CA", "AI", "NZ", "NH", "OZ", "OS", "AV", "SN", "CM", "OU", "MS", "ET", "BR", "HO", "LO", "LH", "SK", "ZH", "SQ", "SA", "LX", "TP", "TG", "TK", "UA", "QK"],
    "skyteam": ["AR", "AM", "UX", "AF", "CI", "MU", "OK", "DL", "GA", "AZ", "KQ", "KL", "KE", "ME", "SV", "RO", "VN", "MF"]
  },
  "saverBookingClasses": {
    "staralliance": ["X", "I", "O"],
    "AA": ["T", "U", "X", "Z"],
    "HA": ["T", "D"]
  },
  "excludeAirlines": ["1I", "FX", "KH", "5X", "8C", "KZ", "5Y", "OO", "K4", "NC", "4Y", "D0", "CK"],
  "chaseUnsupportedAirlines": ["WN"],
  "scrapers": [
    {
      "name": "aa",
      "supportedAirlines": ["AA", "UL", "S7", "RJ", "QR", "QF", "MH", "IB", "HA", "AY", "FJ", "9K", "BA", "AS", "TN", "CX"],
      "nativeAirline": "AA"
    },
    {
      "name": "aeroplan",
      "supportedAirlines": ["staralliance", "GF", "EY", "JU", "CX", "G3", "OY", "UL", "UK"],
      "nativeAirline": "AC"
    },
    {
      "name": "alaska",
      "supportedAirlines": ["AS", "EI", "AA", "BA", "CX", "DE", "LY", "EK", "FJ", "AY", "AU", "FI", "JL", "KE", "LA", "KS", "QF", "7H", "SQ"],
      "nativeAirline": "AS"
    },
    {
      "name": "delta",
      "disabled": true,
      "supportedAirlines": ["skyteam", "WS", "VS"],
      "nativeAirline": "DL"
    },
    {
      "name": "jetblue",
      "supportedAirlines": ["B6"],
      "nativeAirline": "B6"
    },
    {
      "name": "skyscanner",
      "disabled": true,
      "supportedAirlines": [],
      "cashOnlyFares": true
    },
    {
      "name": "skiplagged",
      "supportedAirlines": [],
      "cashOnlyFares": true
    },
    {
      "name": "southwest",
      "supportedAirlines": ["WN"],
      "nativeAirline": "WN"
    },
    {
      "name": "united",
      "supportedAirlines": ["staralliance", "EI", "VW", "EN", "AD", "4B", "9K", "WK", "EW", "HA", "HO", "OA", "3M"],
      "nativeAirline": "UA"
    }
  ]
}
